import 'dart:async';
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:share_plus/share_plus.dart';
import '../models/history_item.dart';
import '../services/download_storage.dart';
import '../services/library_service.dart';
import '../services/music_player_service.dart';
import '../theme/neumorphic_widgets.dart';
import 'playlists_screen.dart';
import 'now_playing_screen.dart';

class LibraryScreen extends StatefulWidget {final MusicPlayerService musicPlayer;const LibraryScreen({super.key,required this.musicPlayer});@override State<LibraryScreen> createState()=>_LibraryScreenState();}
class _LibraryScreenState extends State<LibraryScreen>{final _storage=DownloadStorageService();final _library=LibraryService();final _search=TextEditingController();List<HistoryItem> _items=[];bool _loading=true;bool _favoritesOnly=false;StreamSubscription<void>? _historySubscription;
@override void initState(){super.initState();_load();_search.addListener(_searchChanged);_historySubscription=DownloadStorageService.historyChanges.listen((_)=>mounted?_load():null);}
void _searchChanged(){if(mounted)setState((){});}Future<void> _load()async{if(mounted)setState(()=>_loading=true);final items=await _library.load();if(mounted)setState((){_items=items;_loading=false;});}
List<HistoryItem> get _visible{final q=_search.text.trim().toLowerCase();return _items.where((x)=>(!_favoritesOnly||x.favorite)&&(q.isEmpty||x.title.toLowerCase().contains(q)||x.artist.toLowerCase().contains(q))).toList();}
Future<void> _play(HistoryItem item)async{if(!await File(item.localPath).exists()){_snack('Audio file not found.');return;}await widget.musicPlayer.play(item,source:_visible);}Future<void> _favorite(HistoryItem item)async{await _library.toggleFavorite(item.id);await _load();}Future<void> _delete(HistoryItem item)async{if(widget.musicPlayer.current?.id==item.id)await widget.musicPlayer.clearQueue();await _storage.deleteHistoryItem(item.id);await _load();}
Future<void> _rename(HistoryItem item)async{final c=TextEditingController(text:item.title);final v=await showDialog<String>(context:context,builder:(_)=>AlertDialog(title:const Text('Rename song'),content:TextField(controller:c,autofocus:true),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(context,c.text),child:const Text('Save'))]));c.dispose();if(v!=null){try{await _library.rename(item,v);await _load();}catch(e){_snack(e.toString());}}}
void _snack(String text)=>ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(text)));String _size(int b)=>b<1048576?'${(b/1024).toStringAsFixed(1)} KB':'${(b/1048576).toStringAsFixed(1)} MB';
@override void dispose(){_historySubscription?.cancel();_search.removeListener(_searchChanged);_search.dispose();super.dispose();}
@override Widget build(BuildContext context)=>AnimatedBuilder(animation:widget.musicPlayer,builder:(context,_){final player=widget.musicPlayer;return Scaffold(appBar:AppBar(title:const Text('Music Library'),actions:[NeuIconButton(icon:Icons.queue_music_rounded,onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>PlaylistsScreen(library:_items,musicPlayer:player)))),const SizedBox(width:8),NeuIconButton(icon:Icons.refresh_rounded,onPressed:_load),const SizedBox(width:12)]),body:Column(children:[Padding(padding:const EdgeInsets.all(16),child:Row(children:[Expanded(child:TextField(controller:_search,decoration:const InputDecoration(hintText:'Search songs or artists',prefixIcon:Icon(Icons.search)))),const SizedBox(width:12),NeuIconButton(icon:_favoritesOnly?Icons.favorite:Icons.favorite_border,active:_favoritesOnly,onPressed:()=>setState(()=>_favoritesOnly=!_favoritesOnly))])),Expanded(child:_loading?const Center(child:CircularProgressIndicator()):_visible.isEmpty?const Center(child:Text('No songs found')):ListView.builder(padding:const EdgeInsets.fromLTRB(16,0,16,110),itemCount:_visible.length,itemBuilder:(_,i)=>_tile(_visible[i],player))),if(player.current!=null)_playerBar(player)]);});
Widget _tile(HistoryItem item,MusicPlayerService player){final active=player.current?.id==item.id;return Padding(padding:const EdgeInsets.only(bottom:12),child:NeuSurface(child:Row(children:[ClipRRect(borderRadius:BorderRadius.circular(12),child:SizedBox(width:54,height:54,child:item.thumbnail.isEmpty?const Icon(Icons.music_note):Image.network(item.thumbnail,fit:BoxFit.cover,errorBuilder:(_,__,___)=>const Icon(Icons.music_note)))),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(item.title,maxLines:1,overflow:TextOverflow.ellipsis,style:const TextStyle(fontWeight:FontWeight.w700)),const SizedBox(height:4),Text('${item.artist} • ${_size(item.fileSize)}',style:const TextStyle(color:Colors.white54,fontSize:12))])),NeuIconButton(icon:item.favorite?Icons.favorite:Icons.favorite_border,active:item.favorite,onPressed:()=>_favorite(item)),const SizedBox(width:5),NeuIconButton(icon:active&&player.playing?Icons.pause:Icons.play_arrow,active:active,onPressed:()=>_play(item)),PopupMenuButton<String>(onSelected:(v){if(v=='rename')_rename(item);if(v=='share')Share.shareXFiles([XFile(item.localPath)],text:item.title);if(v=='delete')_delete(item);},itemBuilder:(_)=>const[PopupMenuItem(value:'rename',child:Text('Rename')),PopupMenuItem(value:'share',child:Text('Share')),PopupMenuItem(value:'delete',child:Text('Delete'))])])));}
Widget _playerBar(MusicPlayerService player){final duration=player.duration;final position=player.position;final max=duration.inMilliseconds>0?duration.inMilliseconds.toDouble():1.0;final value=position.inMilliseconds.clamp(0,duration.inMilliseconds).toDouble();return Padding(padding:const EdgeInsets.fromLTRB(12,0,12,12),child:NeuSurface(padding:const EdgeInsets.symmetric(horizontal:8,vertical:4),child:GestureDetector(onTap:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>NowPlayingScreen(player:player))),child:Column(mainAxisSize:MainAxisSize.min,children:[Row(children:[Expanded(child:Text(player.current!.title,maxLines:1,overflow:TextOverflow.ellipsis)),NeuIconButton(icon:Icons.skip_previous,onPressed:player.previous),NeuIconButton(icon:player.playing?Icons.pause:Icons.play_arrow,active:true,onPressed:player.playing?player.pause:player.resume),NeuIconButton(icon:Icons.skip_next,onPressed:player.next)]),Slider(value:value,max:max,onChanged:duration.inMilliseconds==0?null:(v)=>player.seek(Duration(milliseconds:v.toInt()))) ]))));}
}
