import 'dart:io';
import 'package:flutter/material.dart';
import 'package:share_plus/share_plus.dart';
import '../models/history_item.dart';
import '../services/download_storage.dart';
import '../services/library_service.dart';
import '../services/music_player_service.dart';
import 'playlists_screen.dart';

class LibraryScreen extends StatefulWidget {
  final MusicPlayerService musicPlayer;
  const LibraryScreen({super.key, required this.musicPlayer});
  @override State<LibraryScreen> createState()=>_LibraryScreenState();
}
class _LibraryScreenState extends State<LibraryScreen>{
  final _storage=DownloadStorageService(),_library=LibraryService(),_search=TextEditingController();
  List<HistoryItem> _items=[]; bool _loading=true,_favoritesOnly=false;
  @override void initState(){super.initState();_load();_search.addListener((){if(mounted)setState((){});});}
  Future<void> _load()async{if(mounted)setState(()=>_loading=true);final x=await _library.load();if(mounted)setState((){_items=x;_loading=false;});}
  List<HistoryItem> get _visible{final q=_search.text.trim().toLowerCase();return _items.where((x)=>(_favoritesOnly?!x.favorite:true)&&(q.isEmpty||x.title.toLowerCase().contains(q)||x.artist.toLowerCase().contains(q))).toList();}
  Future<void> _play(HistoryItem item)async{if(!await File(item.localPath).exists()){_snack('Audio file not found.');return;}await widget.musicPlayer.play(item,source:_visible);}
  Future<void> _favorite(HistoryItem item)async{await _library.toggleFavorite(item.id);await _load();}
  Future<void> _delete(HistoryItem item)async{if(widget.musicPlayer.current?.id==item.id)await widget.musicPlayer.clearQueue();await _storage.deleteHistoryItem(item.id);await _load();}
  Future<void> _rename(HistoryItem item)async{final c=TextEditingController(text:item.title);final value=await showDialog<String>(context:context,builder:(_)=>AlertDialog(title:const Text('Rename song'),content:TextField(controller:c,autofocus:true),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(context,c.text),child:const Text('Save'))]));c.dispose();if(value!=null)try{await _library.rename(item,value);await _load();}catch(e){_snack(e.toString());}}
  void _snack(String s)=>ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(s)));String _size(int b)=>b<1024*1024?'${(b/1024).toStringAsFixed(1)} KB':'${(b/1024/1024).toStringAsFixed(1)} MB';
  @override void dispose(){_search.dispose();super.dispose();}
  @override Widget build(BuildContext context)=>AnimatedBuilder(animation:widget.musicPlayer,builder:(context,_){final p=widget.musicPlayer;return Scaffold(appBar:AppBar(title:const Text('Music Library',style:TextStyle(fontWeight:FontWeight.bold)),actions:[IconButton(onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>PlaylistsScreen(library:_items))),icon:const Icon(Icons.queue_music_rounded)),IconButton(onPressed:_load,icon:const Icon(Icons.refresh_rounded))]),body:Column(children:[Padding(padding:const EdgeInsets.fromLTRB(16,8,16,4),child:Row(children:[Expanded(child:TextField(controller:_search,decoration:InputDecoration(hintText:'Search songs or artists',prefixIcon:const Icon(Icons.search),filled:true,fillColor:const Color(0xFF15151B),border:OutlineInputBorder(borderRadius:BorderRadius.all(Radius.circular(14)),borderSide:BorderSide.none)))),const SizedBox(width:8),IconButton(onPressed:()=>setState(()=>_favoritesOnly=!_favoritesOnly),icon:Icon(_favoritesOnly?Icons.favorite:Icons.favorite_border,color:_favoritesOnly?const Color(0xFFEF5350):null))])),Expanded(child:_loading?const Center(child:CircularProgressIndicator()):_visible.isEmpty?const Center(child:Text('No songs found',style:TextStyle(color:Colors.white54))):ListView.builder(padding:const EdgeInsets.fromLTRB(16,8,16,110),itemCount:_visible.length,itemBuilder:(_,i)=>_tile(_visible[i],p))),if(p.current!=null)_playerBar(p)]);});
  Widget _tile(HistoryItem x,MusicPlayerService p){final active=p.current?.id==x.id;return Card(color:active?const Color(0xFF211B32):const Color(0xFF15151B),margin:const EdgeInsets.only(bottom:8),child:ListTile(contentPadding:const EdgeInsets.symmetric(horizontal:10,vertical:3),leading:ClipRRect(borderRadius:BorderRadius.circular(9),child:SizedBox(width:52,height:52,child:x.thumbnail.isNotEmpty?Image.network(x.thumbnail,fit:BoxFit.cover,errorBuilder:(_,__,___)=>const Icon(Icons.music_note)):const Icon(Icons.music_note))),title:Text(x.title,maxLines:1,overflow:TextOverflow.ellipsis,style:const TextStyle(fontWeight:FontWeight.w700)),subtitle:Text('${x.artist} • ${_size(x.fileSize)}',maxLines:1,overflow:TextOverflow.ellipsis,style:const TextStyle(color:Colors.white54)),trailing:Row(mainAxisSize:MainAxisSize.min,children:[IconButton(onPressed:()=>_favorite(x),icon:Icon(x.favorite?Icons.favorite:Icons.favorite_border,color:x.favorite?const Color(0xFFEF5350):Colors.white54)),IconButton(onPressed:()=>_play(x),icon:Icon(active&&p.playing?Icons.pause_circle_filled:Icons.play_circle_fill,color:const Color(0xFF8B5CF6),size:32)),PopupMenuButton<String>(onSelected:(v){if(v=='rename')_rename(x);if(v=='share')Share.shareXFiles([XFile(x.localPath)],text:x.title);if(v=='delete')_delete(x);},itemBuilder:(_)=>const[PopupMenuItem(value:'rename',child:Text('Rename')),PopupMenuItem(value:'share',child:Text('Share')),PopupMenuItem(value:'delete',child:Text('Delete'))])])));}
  Widget _playerBar(MusicPlayerService p){final d=p.duration,pos=p.position,max=d.inMilliseconds>0?d.inMilliseconds.toDouble():1.0,val=pos.inMilliseconds.clamp(0,d.inMilliseconds).toDouble();return Container(decoration:const BoxDecoration(color:Color(0xFF211B32)),padding:const EdgeInsets.fromLTRB(12,8,12,10),child:Column(mainAxisSize:MainAxisSize.min,children:[Row(children:[Expanded(child:Text(p.current!.title,maxLines:1,overflow:TextOverflow.ellipsis,style:const TextStyle(fontWeight:FontWeight.bold))),IconButton(onPressed:p.previous,icon:const Icon(Icons.skip_previous_rounded)),IconButton(onPressed:p.playing?p.pause:p.resume,icon:Icon(p.playing?Icons.pause_rounded:Icons.play_arrow_rounded)),IconButton(onPressed:p.next,icon:const Icon(Icons.skip_next_rounded)),IconButton(onPressed:()=>p.setShuffle(!p.shuffle),icon:Icon(Icons.shuffle_rounded,color:p.shuffle?const Color(0xFF8B5CF6):null)),IconButton(onPressed:()=>p.setRepeat(!p.repeat),icon:Icon(Icons.repeat_rounded,color:p.repeat?const Color(0xFF8B5CF6):null))]),Slider(value:val,max:max,onChanged:d.inMilliseconds==0?null:(v)=>p.seek(Duration(milliseconds:v.toInt()))) ]));}
}
