import 'package:flutter/material.dart';
import '../models/history_item.dart';
import '../services/download_storage.dart';
import '../services/music_player_service.dart';
import '../theme/neumorphic_widgets.dart';

class PlaylistsScreen extends StatefulWidget{final List<HistoryItem> library;final MusicPlayerService musicPlayer;const PlaylistsScreen({super.key,required this.library,required this.musicPlayer});@override State<PlaylistsScreen> createState()=>_PlaylistsScreenState();}
class _PlaylistsScreenState extends State<PlaylistsScreen>{final _storage=DownloadStorageService();Map<String,List<String>> _playlists={};@override void initState(){super.initState();_load();}Future<void> _load()async{final p=await _storage.loadPlaylists();if(mounted)setState(()=>_playlists=p);}Future<void> _create()async{final n=await _showName();if(!mounted||n==null||n.isEmpty)return;if(_playlists.containsKey(n)){_snack('Playlist already exists.');return;}final u=<String,List<String>>{..._playlists,n:<String>[]};await _storage.savePlaylists(u);if(mounted)setState(()=>_playlists=u);}Future<String?> _showName()=>showDialog<String>(context:context,builder:(_)=>const _CreatePlaylistDialog());Future<void> _delete(String n)async{final u=Map<String,List<String>>.from(_playlists)..remove(n);await _storage.savePlaylists(u);if(mounted)setState(()=>_playlists=u);}Future<void> _edit(String n)async{final selected=<String>{...(_playlists[n]??const<String>[])};final saved=await showDialog<bool>(context:context,builder:(_)=>_EditPlaylistDialog(name:n,library:widget.library,selected:selected));if(!mounted||saved!=true)return;final u=<String,List<String>>{..._playlists,n:selected.toList()};await _storage.savePlaylists(u);if(mounted)setState(()=>_playlists=u);}Future<void> _play(String n)async{final ids=_playlists[n]??const<String>[];final songs=<HistoryItem>[];for(final id in ids){for(final song in widget.library){if(song.id==id){songs.add(song);break;}}}if(songs.isEmpty){_snack('This playlist has no available songs.');return;}await widget.musicPlayer.play(songs.first,source:songs);}void _snack(String t){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(t)));}
@override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Playlists')),floatingActionButton:FloatingActionButton(onPressed:_create,child:const Icon(Icons.add)),body:_playlists.isEmpty?const Center(child:Text('No playlists yet')):ListView(padding:const EdgeInsets.all(16),children:_playlists.entries.map((e)=>Padding(padding:const EdgeInsets.only(bottom:12),child:NeuSurface(child:Row(children:[NeuIconButton(icon:Icons.queue_music,onPressed:()=>_play(e.key)),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(e.key,style:const TextStyle(fontWeight:FontWeight.bold)),const SizedBox(height:4),Text('${e.value.length} songs',style:const TextStyle(color:Colors.white54,fontSize:12))])),PopupMenuButton<String>(onSelected:(v){if(v=='play')_play(e.key);if(v=='edit')_edit(e.key);if(v=='delete')_delete(e.key);},itemBuilder:(_)=>const[PopupMenuItem(value:'play',child:Text('Play playlist')),PopupMenuItem(value:'edit',child:Text('Add / edit songs')),PopupMenuItem(value:'delete',child:Text('Delete playlist'))])]))).toList()));}
}
class _CreatePlaylistDialog extends StatefulWidget{const _CreatePlaylistDialog();@override State<_CreatePlaylistDialog> createState()=>_CreatePlaylistDialogState();}class _CreatePlaylistDialogState extends State<_CreatePlaylistDialog>{late final TextEditingController _controller;@override void initState(){super.initState();_controller=TextEditingController();}@override void dispose(){_controller.dispose();super.dispose();}void _submit(){final n=_controller.text.trim();Navigator.of(context).pop(n.isEmpty?null:n);}@override Widget build(BuildContext context)=>AlertDialog(title:const Text('New playlist'),content:TextField(controller:_controller,autofocus:true,textInputAction:TextInputAction.done,onSubmitted:(_)=>_submit(),decoration:const InputDecoration(hintText:'Playlist name')),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('Cancel')),FilledButton(onPressed:_submit,child:const Text('Create'))]);}
class _EditPlaylistDialog extends StatefulWidget{final String name;final List<HistoryItem> library;final Set<String> selected;const _EditPlaylistDialog({required this.name,required this.library,required this.selected});@override State<_EditPlaylistDialog> createState()=>_EditPlaylistDialogState();}class _EditPlaylistDialogState extends State<_EditPlaylistDialog>{late final Set<String> _selected;@override void initState(){super.initState();_selected={<String>{...widget.selected}}.expand((x)=>x).toSet();}@override Widget build(BuildContext context)=>AlertDialog(title:Text('Songs in ${widget.name}'),content:SizedBox(width:double.maxFinite,height:400,child:widget.library.isEmpty?const Center(child:Text('No downloaded songs available.')):ListView(children:widget.library.map((s)=>CheckboxListTile(value:_selected.contains(s.id),onChanged:(v)=>setState(()=>v==true?_selected.add(s.id):_selected.remove(s.id)),title:Text(s.title,maxLines:1,overflow:TextOverflow.ellipsis),subtitle:Text(s.artist))).toList())),actions:[TextButton(onPressed:()=>Navigator.pop(context,false),child:const Text('Cancel')),FilledButton(onPressed:(){widget.selected..clear()..addAll(_selected);Navigator.pop(context,true);},child:const Text('Save'))]);}
