import 'package:flutter/material.dart';
import '../models/song_info.dart';
import '../services/downloader_api.dart';
import '../services/download_manager_service.dart';
import '../theme/neumorphic_widgets.dart';
import 'progress_screen.dart';

class PreviewScreen extends StatefulWidget {final SongInfo songInfo;final DownloaderApiService apiService;final DownloadManagerService downloadManager;final VoidCallback onOpenLibrary;const PreviewScreen({super.key,required this.songInfo,required this.apiService,required this.downloadManager,required this.onOpenLibrary});@override State<PreviewScreen> createState()=>_PreviewScreenState();}
class _PreviewScreenState extends State<PreviewScreen>{bool _starting=false;String? _error;String _formatDuration(int s)=>s<=0?'Unknown duration':'${s~/60}:${(s%60).toString().padLeft(2,'0')}';
Future<void> _startDownload()async{setState((){_starting=true;_error=null;});try{final id=await widget.downloadManager.enqueue(widget.songInfo.webpageUrl);if(!mounted)return;Navigator.pushReplacement(context,MaterialPageRoute(builder:(_)=>ProgressScreen(jobId:id,songInfo:widget.songInfo,apiService:widget.apiService,downloadManager:widget.downloadManager,onOpenLibrary:widget.onOpenLibrary)));}catch(e){if(mounted)setState((){_error=e.toString();_starting=false;});}}
@override Widget build(BuildContext context){final song=widget.songInfo;return Scaffold(appBar:AppBar(title:const Text('Song Preview')),body:SafeArea(child:ListView(padding:const EdgeInsets.all(20),children:[NeuSurface(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[ClipRRect(borderRadius:BorderRadius.circular(16),child:AspectRatio(aspectRatio:16/9,child:song.thumbnail.isNotEmpty?Image.network(song.thumbnail,fit:BoxFit.cover,errorBuilder:(_,__,___)=>const ColoredBox(color:Color(0xFF24242B),child:Icon(Icons.music_note_rounded,size:64))):const ColoredBox(color:Color(0xFF24242B),child:Icon(Icons.music_note_rounded,size:64)))),const SizedBox(height:18),Text(song.title,style:const TextStyle(fontSize:21,fontWeight:FontWeight.bold)),const SizedBox(height:5),Text(song.artist,style:const TextStyle(color:Colors.white60)),const SizedBox(height:10),Row(children:[const Icon(Icons.timer_outlined,size:16,color:Colors.white54),const SizedBox(width:6),Text(_formatDuration(song.duration),style:const TextStyle(color:Colors.white54))]),const SizedBox(height:20),NeuSurface(padding:const EdgeInsets.all(14),child:const Row(children:[Icon(Icons.high_quality_rounded,color:Color(0xFF8B5CF6)),SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Best Available Audio',style:TextStyle(fontWeight:FontWeight.w700)),SizedBox(height:3),Text('Original source stream • Converted safely to MP3',style:TextStyle(fontSize:12,color:Colors.white60))]))])),const SizedBox(height:18),NeuButton(onPressed:_starting?null:_startDownload,child:Row(mainAxisAlignment:MainAxisAlignment.center,children:[_starting?const SizedBox(width:18,height:18,child:CircularProgressIndicator(strokeWidth:2)):const Icon(Icons.download_rounded),const SizedBox(width:8),Text(_starting?'Adding to downloads…':'Download Audio')])),if(_error!=null)...[const SizedBox(height:14),Text(_error!,style:const TextStyle(color:Colors.redAccent,fontSize:13))]])])));}
}
